apiVersion: v1
kind: Service
metadata:
  name: front-svc
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: frontend
